// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ColorSense",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ColorSense",
            targets: ["AppModule"],
            bundleIdentifier: "com.zanivan.br.ColorSense",
            teamIdentifier: "55AU2SQW7Z",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ColorSense needs to access your camera to provide an accurate simulation of how people with color blindness perceive the world around them.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)